apiVersion: v1
kind: Namespace
metadata:
    name: bar-dev
---
apiVersion: v1
kind: Namespace
metadata:
    name: bar-prod
---
apiVersion: v1
kind: Namespace
metadata:
    name: bar-qa
---
apiVersion: v1
kind: Namespace
metadata:
    name: bar-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-reader
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-reader
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-cluster-admin
  namespace: bar
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-reader
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: bar
subjects:
- kind: ServiceAccount
  name: sa-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cluster-admin
